# These are supported funding model platforms

github: # mdakashhossain1
patreon: # Your Patreon username
open_collective: # Your Open Collective username
ko_fi: # Your Ko-fi username
buy_me_a_coffee: # Your Buy Me A Coffee username
custom: ['https://github.com/mdakashhossain1/SubTranscribe-Studio']
